# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2896b64ea0c5b7bb38ef413c261f99af48dd50433653072974b128819c1dcd0cd1adb9080fbccbed5bc195082236dd7f1665e3f43008c627beab9a02f903c81a

test:
  secret_key_base: abf6ad01dcebd3a618e147510c0969889a025fdf3b905fabf50584f3fcba651576916ae48cff5d14b062add42f82dd02c07719d850407607f66e82fb30c70552

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
